### ISSUE TITLE
Compilation errors after repo sync on September, 16

### ISSUE THREAD

**Issue by acras01** [AospExtended/platform_frameworks_opt_telephony#1]
After today's repo sync I've got errors

https://del.dog/ofaturaqez.coffeescript

**Comment by lxl6125** [comment]
I also encountered the same error.

**Comment by acras01** [comment]
I think there is missing file

https://github.com/PotatoProject/frameworks_base/blob/9528909fd361d6f608ca7549c8a0c72d7b0b3f65/telephony/java/com/android/internal/telephony/ISmsBaseImpl.java

**Comment by raystef66** [comment]
same error https://del.dog/ulojukoqay.coffeescript

**Comment by kevte89** [comment]
I also had this mistake yesterday, and am surprised why

https://del.dog/orelusikez

**Comment by sb6596** [comment]
Check now

**Comment by raystef66** [comment]
repo sync --force-sync again and it completed my build ok now

**Comment by acras01** [comment]
Fixed

вт, 17 сент. 2019 г., 16:56 raystef66 <notifications@github.com>:

**Comment by kevte89** [comment]
It is finally thanks again
